// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcT0
Rcpp::List calcT0(arma::mat tXUs, arma::mat yresid, arma::mat powV, int nperm);
RcppExport SEXP aSPU_calcT0(SEXP tXUsSEXP, SEXP yresidSEXP, SEXP powVSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type tXUs(tXUsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yresid(yresidSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    __result = Rcpp::wrap(calcT0(tXUs, yresid, powV, nperm));
    return __result;
END_RCPP
}
// calcT0sim
Rcpp::List calcT0sim(arma::mat CvSqrt, arma::mat powV, int nperm);
RcppExport SEXP aSPU_calcT0sim(SEXP CvSqrtSEXP, SEXP powVSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    __result = Rcpp::wrap(calcT0sim(CvSqrt, powV, nperm));
    return __result;
END_RCPP
}
