// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// calcT0
Rcpp::List calcT0(arma::mat tXUs, arma::mat yresid, arma::mat powV, int nperm);
RcppExport SEXP aSPU_calcT0(SEXP tXUsSEXP, SEXP yresidSEXP, SEXP powVSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type tXUs(tXUsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type yresid(yresidSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calcT0(tXUs, yresid, powV, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calcT0sim
Rcpp::List calcT0sim(arma::mat CvSqrt, arma::mat powV, int nperm);
RcppExport SEXP aSPU_calcT0sim(SEXP CvSqrtSEXP, SEXP powVSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type CvSqrt(CvSqrtSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(calcT0sim(CvSqrt, powV, nperm));
    return rcpp_result_gen;
END_RCPP
}
// calcT0simM2
Rcpp::List calcT0simM2(arma::mat A, arma::mat B, arma::mat powV, arma::mat pow2V, int nperm, int Pval, arma::mat Ts);
RcppExport SEXP aSPU_calcT0simM2(SEXP ASEXP, SEXP BSEXP, SEXP powVSEXP, SEXP pow2VSEXP, SEXP npermSEXP, SEXP PvalSEXP, SEXP TsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type powV(powVSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pow2V(pow2VSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    Rcpp::traits::input_parameter< int >::type Pval(PvalSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ts(TsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcT0simM2(A, B, powV, pow2V, nperm, Pval, Ts));
    return rcpp_result_gen;
END_RCPP
}
