# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call('aSPU_set_seed', PACKAGE = 'aSPU', seed))
}

avg_rank <- function(x) {
    .Call('aSPU_avg_rank', PACKAGE = 'aSPU', x)
}

calcT0 <- function(tXUs, yresid, powV, nperm) {
    .Call('aSPU_calcT0', PACKAGE = 'aSPU', tXUs, yresid, powV, nperm)
}

calcT0sim <- function(CvSqrt, powV, nperm) {
    .Call('aSPU_calcT0sim', PACKAGE = 'aSPU', CvSqrt, powV, nperm)
}

calcT0simM2 <- function(A, B, powV, pow2V, nperm, Pval, Ts) {
    .Call('aSPU_calcT0simM2', PACKAGE = 'aSPU', A, B, powV, pow2V, nperm, Pval, Ts)
}

aSPUpathEngine <- function(tXUs, r, pow1, pow2, nGenes, n_perm, k, nSNPs0, Ts2, s) {
    .Call('aSPU_aSPUpathEngine', PACKAGE = 'aSPU', tXUs, r, pow1, pow2, nGenes, n_perm, k, nSNPs0, Ts2, s)
}

aSPUpermEngine <- function(tXUs, r, pow1, n_perm, Ts, s) {
    .Call('aSPU_aSPUpermEngine', PACKAGE = 'aSPU', tXUs, r, pow1, n_perm, Ts, s)
}

aSPUsPathEngine <- function(CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, Ps, nSNPs0, StdTs) {
    .Call('aSPU_aSPUsPathEngine', PACKAGE = 'aSPU', CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, Ps, nSNPs0, StdTs)
}

aSPUsPathEngine2 <- function(CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, Ps, nSNPs0, Ts2, s) {
    .Call('aSPU_aSPUsPathEngine2', PACKAGE = 'aSPU', CH, CHcovSq, pow1, pow2, nGenes, n_perm, k, Ps, nSNPs0, Ts2, s)
}

