# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcT0 <- function(tXUs, yresid, powV, nperm) {
    .Call('aSPU_calcT0', PACKAGE = 'aSPU', tXUs, yresid, powV, nperm)
}

calcT0sim <- function(CvSqrt, powV, nperm) {
    .Call('aSPU_calcT0sim', PACKAGE = 'aSPU', CvSqrt, powV, nperm)
}

